server:
  port: 8000

spring:
  #连接池配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-m5ehef7hg63n3d2660o.mysql.rds.aliyuncs.com/klmklm?characterEncoding=UTF-8&allowMultiQueries=true
    username: user
    password: Aa123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
